---
grails:
    profile: web
    codegen:
        defaultPackage: sen1.proxies.pride
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: true
        region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory

environments:
    development:
        dataSource:
            logSql: true
            formatSql: true
            pooled: true
            dbCreate: update
            driverClassName: org.postgresql.Driver
            url: jdbc:postgresql://localhost:5432/sen1-proxy-pride
            username: postgres
            password: 18fhk6vf4d
            properties:
                validationQuery: SELECT 1
                maxActive: 5
                logAbandoned: true
                maxWait: 5000
    test:
        dataSource:
            logSql: true
            formatSql: true
            pooled: true
            driverClassName: org.h2.Driver
            dbCreate: create-drop
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            jndiName: java:comp/env/sen1ProxyPrideDataSource
                     
---
quartz:
    scheduler:
        instanceName: Sen1ProxyPrideQuartzScheduler
        instanceId: AUTO
    threadPool:
        class: org.quartz.simpl.SimpleThreadPool
        threadCount: 2
    jobStore:
        isClustered: true
        tablePrefix: quartz.QRTZ_
        class: org.quartz.impl.jdbcjobstore.JobStoreTX
        driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
        dataSource: sen1ProxyPrideDataSource
        clusterCheckinInterval: 20000

environments:
    development:
        quartz:
            dataSource:
                sen1ProxyPrideDataSource:
                    driver: org.postgresql.Driver
                    URL: jdbc:postgresql://localhost:5432/sen1-proxy-pride
                    user: postgres
                    password: 18fhk6vf4d
                    maxConnections: 2
    production:
        quartz:
            dataSource:
                sen1ProxyPrideDataSource:
                    jndiURL: java:comp/env/sen1ProxyPrideDataSource
            scheduler:
                skipUpdateCheck: true

